//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingLiabilities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQuocThinhEntities : DbContext
    {
        public DBQuocThinhEntities()
            : base("name=DBQuocThinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonDaHoanTraThucTe> DonDaHoanTraThucTes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<DoiSoatVanChuyen> DoiSoatVanChuyens { get; set; }
        public virtual DbSet<DonDi> DonDis { get; set; }
    }
}
