//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingLiabilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiSoatVanChuyen
    {
        public decimal id { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public Nullable<decimal> collection_amount { get; set; }
        public Nullable<decimal> refund_fee { get; set; }
        public Nullable<decimal> delivery_fee { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string code_shop { get; set; }
        public string partners { get; set; }
    }
}
