//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingLiabilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDi
    {
        public decimal id { get; set; }
        public string code { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public string cust_mobile { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> out_date { get; set; }
        public string status { get; set; }
        public string employee { get; set; }
    }
}
