//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingLiabilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapXuatTon
    {
        public decimal id { get; set; }
        public string product_code { get; set; }
        public string color_code { get; set; }
        public string size_code { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> nxt_date { get; set; }
    }
}
