//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingLiabilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public decimal id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string supplier { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
